kind: pipeline
type: docker
name: default

image_pull_secrets:
  - dockerconfigjson

clone:
  disable: true

steps:
- name: install
  image: qwert555312/centos-node:node
  commands:
      - cd /data/key
      - ls
      - chmod 600 node.pem
      - cd /data/htdocs
      - git clone https://git.yinunite.com/base/frontend/ukraine.git test
      - sleep 1
      - cd test
      - npm i 
      - nvm use 16 
      - npm run build 
      - sleep 1
      - zip -r dist.zip dist
      - sleep 1
      - scp -rp -i /data/key/node.pem dist.zip centos@3.17.249.121:/home/centos
